### ISSUE TITLE
Modificación de la GC

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#1]
#### Descripción del cambio:
La Gestión de la Configuración se creó bajo la premisa de que hay diferencia entre **Tag y Release** para nuestro repositorio, pero Github **no distingue** actualmente entre ellos https://stackoverflow.com/a/28500451

#### Objetivo del cambio:
**Modificar ligeramente la GC** para que no sea incorrecta, intentando conservar la funcionalidad actual y relatarlo en el apartado de **"Lecciones aprendidas"**

#### Configuración afectada:
Proyecto_grupo_J/Organizacion/Plan_Gestion_Configuracion.doc

#### Comentario:
Es posible que esta semana encontremos más cambios necesarios en este archivo, por lo que se recomienda no cerrar este issue hasta el día de la entrega.

#### Gravedad (Seleccionar varias en caso de duda):
  - [ ] Alta.
  - [ ] Media.
  - [x] Baja.

**Comment by danielblanco96** [comment]
Estoy a favor del cambio.

**Comment by PabloSB96** [comment]
A favor del cambio

**Comment by Lns-Prt** [comment]
Estoy a favor del cambio.

**Comment by andresgomezvidal** [comment]
He hecho las modificaciones que consideraba necesarias, visibles en el commit 397af69c4e1fc354c72ae1b0e7755795d5adfeb9 
https://github.com/andresgomezvidal/gestion_de_proyectos/commit/397af69c4e1fc354c72ae1b0e7755795d5adfeb9

Considero que se puede cerrar este issue

**Comment by Lns-Prt** [comment]
Apruebo el merge.
