### ISSUE TITLE
Actualizar planificación

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#10]
#### Descripción del cambio:
Una planificación (realizada con Open Project o con el producto open source openproj) que incluya los trabajos realizados para las prácticas anteriores y para esta práctica.

Para una mejor organización, la planificación de cada una de las prácticas será una tarea con las subtareas correspondientes. **Podríamos emplear los issues y agrupar los commits relacionados dentro.** Así quedaría especificado sin dudas, reflejando siempre el tiempo real.

#### Objetivo del cambio:
Actualizar el Gantt

#### Configuración afectada:
Proyecto_grupo_J/Organizacion/ReparticionTrabajoGrupoJ.pod

#### Comentario:
Necesario para la práctica 2.
Debería realizarse al acabar las tareas para no tener que reescribirse.

#### Gravedad (Seleccionar varias en caso de duda):
  - [ ] Alta.
  - [x] Media.
  - [ ] Baja.

**Comment by PabloSB96** [comment]
A favor del cambio

**Comment by andresgomezvidal** [comment]
Creo que se puede integrar en develop

**Comment by PabloSB96** [comment]
Perfecto
