### ISSUE TITLE
Modificación de la GC

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#11]
#### Descripción del cambio:
El issue no se está cerrando automáticamente como se relata que debería ocurrir en la GC, por lo que propongo modificarla

#### Objetivo del cambio:
**Modificar ligeramente la GC** para que no sea incorrecta, intentando conservar la funcionalidad actual y relatarlo en el apartado de **"Lecciones aprendidas"**

#### Configuración afectada:
Proyecto_grupo_J/Organizacion/Plan_Gestion_Configuracion.doc

#### Gravedad (Seleccionar varias en caso de duda):
  - [ ] Alta.
  - [ ] Media.
  - [x] Baja.

**Comment by PabloSB96** [comment]
A favor del cambio

**Comment by andresgomezvidal** [comment]
Considero que está completado el cambio correctamente
