### ISSUE TITLE
Recursos para las actividades

### ISSUE THREAD

**Issue by PabloSB96** [andresgomezvidal/gestion_de_proyectos#12]
#### Descripción del cambio:
Añadir una tabla para completar los Recursos Requeridos para las Actividades

#### Objetivo del cambio:
Añadir un apartado de Recursos Requeridos para las Actividades

#### Configuración afectada:
Proyecto_grupo_J/Proyecto/Memoria_Proyecto.doc

#### Gravedad (Seleccionar varias en caso de duda):
  - [ ] Alta.
  - [x] Media.
  - [ ] Baja.

**Comment by PabloSB96** [comment]
A favor del cambio

**Comment by danielblanco96** [comment]
Acepto cambio

**Comment by andresgomezvidal** [comment]
Aceptado

**Comment by andresgomezvidal** [comment]
Excelente

**Comment by PabloSB96** [comment]
Propongo cerrar el issue
