### ISSUE TITLE
Cambios en nombres de archivo

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#14]
#### Descripción del cambio:
Renombrar los archivos de entrega, para no hacerlo manualmente en local antes de la misma

#### Objetivo del cambio:
Renombrar los archivos de entrega

#### Configuración afectada:
Proyecto_grupo_J/Organizacion/Plan_Gestion_Configuracion.docx              a  Proyecto_grupo_J/Organizacion/GrpJ_PRO_171012_PlanGC.docx

Proyecto_grupo_J/Practicas/Organización del trabajo de la practica.docx    a  Proyecto_grupo_J/Practicas/GrpJ_ISI_171012_OrganizacionTrabajo.docx
Proyecto_grupo_J/Practicas/ReparticionTrabajoGrupoJ.pod                    a  Proyecto_grupo_J/Practicas/GrpJ_ISI_171012_ReparticionTrabajo.pod

Proyecto_grupo_J/Proyecto/Acta de constitución del proyecto.docx           a  Proyecto_grupo_J/Proyecto/GrpJ_ACR_171005_ActaConstitucion.docx
Proyecto_grupo_J/Proyecto/Registro de Incidentes.docx                      a  Proyecto_grupo_J/Proyecto/GrpJ_ARI_171012_RegistroIncidentes.docx
Proyecto_grupo_J/Proyecto/Catalogo de Requisitos.xlsx                      a  Proyecto_grupo_J/Proyecto/GrpJ_CRQ_171012_CatalogoRequisitos.xlsx
Proyecto_grupo_J/Proyecto/Diagramas/requisitos_funcionales.mdj             a  Proyecto_grupo_J/Proyecto/GrpJ_ERQ_171012_DiagramaRequisitosFuncionales.mdj
Proyecto_grupo_J/Proyecto/Estimación de Requisitos_subgrupo1.ods           a  Proyecto_grupo_J/Proyecto/GrpJ_ERQ_171012_EstimacionRequisitosSubgrupo1.xlsl
Proyecto_grupo_J/Proyecto/Estimación de Requisitos_subgrupo2.ods           a  Proyecto_grupo_J/Proyecto/GrpJ_ERQ_171012_EstimacionRequisitosSubgrupo2.xlsl
Proyecto_grupo_J/Proyecto/Estimación de Requisitos.ods                     a  Proyecto_grupo_J/Proyecto/GrpJ_ERQ_171012_EstimacionRequisitos.xlsl
Proyecto_grupo_J/Proyecto/Memoria_Proyecto.docx                            a  Proyecto_grupo_J/Proyecto/GrpJ_PLP_171012_MemoriaProyecto.docx
Proyecto_grupo_J/Proyecto/RBS.xml                                          a  Proyecto_grupo_J/Proyecto/GrpJ_PRS_171012_RBS.xml

#### Comentario:
Proyecto_grupo_J/Proyecto/Diagramas/requisitos_funcionales.mdj subiría una carpeta

#### Gravedad (Seleccionar varias en caso de duda):
  - [] Alta.
  - [] Media.
  - [x] Baja.

**Comment by PabloSB96** [comment]
A favor del cambio

**Comment by andresgomezvidal** [comment]
Creo que esto se puede cerrar ya

**Comment by PabloSB96** [comment]
A favor de cerrar el issue
