### ISSUE TITLE
Cambiar .gitignore

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#15]
#### Descripción del cambio:
.gitignore permite ignorar ciertos archivos a tratar como si fuesen del proyecto. Pueden usarse expresiones regulares. Se consigue evitar _fallos humanos_, por ejemplo de tener abierto un documento de word mientras se suben cambios de local

#### Objetivo del cambio:
Prevenir archivos indeseados en el proyecto.
Concretamente estaba pensando en https://www.gitignore.io/api/vim%2Cjava%2Cwindows%2Cnetbeans%2Clibreoffice%2Cmicrosoftoffice

#### Configuración afectada:
.gitignore

#### Gravedad (Seleccionar varias en caso de duda):
  - [] Alta.
  - [] Media.
  - [x] Baja.

**Comment by PabloSB96** [comment]
A favor del cambio

**Comment by andresgomezvidal** [comment]
Creo que esto se puede cerrar ya

**Comment by PabloSB96** [comment]
ok, a favor de cerrar el issue
