### ISSUE TITLE
xlsl a ods

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#16]
#### Descripción del cambio:
xlsl a ods

#### Objetivo del cambio:
Que compile en la corrección

#### Configuración afectada:
Proyecto_grupo_J/Proyecto/EstimacionRequisitos.xlsl
Proyecto_grupo_J/Proyecto/EstimacionRequisitosSubgrupo1.xlsl
Proyecto_grupo_J/Proyecto/EstimacionRequisitosSubgrupo2.xlsl

#### Gravedad (Seleccionar varias en caso de duda):
  - [] Alta.
  - [] Media.
  - [x] Baja.

**Comment by PabloSB96** [comment]
A favor del cambio

**Comment by andresgomezvidal** [comment]
Hecho. Ya se puede hacer merge

**Comment by PabloSB96** [comment]
Ok
