### ISSUE TITLE
indice memoria

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#17]
#### Descripción del cambio:
Actualizar el formato de la memoria

#### Objetivo del cambio:
Que funcione correctamente el índice y modificar el nombre que aparece en la cabecera del documento al nombre que se colocó en #14 

#### Configuración afectada:
Proyecto_grupo_J/Proyecto/GrpJ_PLP_MemoriaProyecto.docx

#### Gravedad (Seleccionar varias en caso de duda):
  - [] Alta.
  - [] Media.
  - [x] Baja.

**Comment by PabloSB96** [comment]
A favor del cambio

**Comment by PabloSB96** [comment]
Creo que ya se puede cerrar este issue

**Comment by andresgomezvidal** [comment]
ok
