### ISSUE TITLE
Corregir Gestión de la Configuración

### ISSUE THREAD

**Issue by Lns-Prt** [andresgomezvidal/gestion_de_proyectos#18]
#### Descripción del cambio:
Modificar el documento que describe el proceso de Gestión de la Configuración de la organización, aplicando correcciones y mejoras. Actualizar la memoria si hace falta.

#### Objetivo del cambio:
Corregir errores y mejorar el proceso y la descripción de la Gestión de la Configuración.

#### Configuración afectada:
Proyecto_grupo_J/Organizacion/GrpJ_PRO_PlanGC.docx
Proyecto_grupo_J/Proyecto/GrpJ_PLP_MemoriaProyecto.docx

#### Gravedad (Seleccionar varias en caso de duda):
  - [x] Alta.
  - [] Media.
  - [] Baja.

**Comment by andresgomezvidal** [comment]
Muy bien

**Comment by andresgomezvidal** [comment]
No tenemos que entregarlo para esta entrega si no la final. Pero se recomienda hacerlo antes. Debido a otras prioridades el trabajo en esto ahora mismo no es activo. Probablemente vuelva a trabajar sobre ello dentro de una semana

**Comment by andresgomezvidal** [comment]
Creo que se puede cerrar

**Comment by PabloSB96** [comment]
A favor del cierre.

**Comment by andresgomezvidal** [comment]
Ahora sí creo que se puede cerrar

**Comment by PabloSB96** [comment]
A favor del cierre.
