### ISSUE TITLE
Creación EDT

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#19]
#### Descripción del cambio:
Añadir el EDT a la memoria

#### Objetivo del cambio:
Añadir la imagen y descripción básica a la memoria

#### Configuración afectada:
graficas/EDT.png
Proyecto_grupo_J/Proyecto/GrpJ_PLP_MemoriaProyecto.docx

#### Gravedad (Seleccionar varias en caso de duda):
  - [] Alta.
  - [] Media.
  - [x] Baja.

**Comment by Lns-Prt** [comment]
Estoy de acuerdo con el cambio.

**Comment by PabloSB96** [comment]
Creo que ya se puede cerrar este issue

**Comment by PabloSB96** [comment]
Propongo cerrar el issue
