### ISSUE TITLE
Registro de Interesados

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#2]
#### Descripción del cambio:
Documentar todos los detalles relacionados con los interesados identificados y esta lista

#### Objetivo del cambio:
Generación de los documentos necesarios para identificar a los Interesados del proyecto

#### Configuración afectada:
Proyecto_grupo_J/Proyecto/Registro de Interesados.docx
Proyecto_grupo_J/Proyecto/Plan de Gestión de los Interesados.docx

#### Comentario:
Necesario para la práctica 2

#### Gravedad (Seleccionar varias en caso de duda):
  - [x] Alta.
  - [ ] Media.
  - [ ] Baja.

**Comment by Lns-Prt** [comment]
Estoy a favor del cambio.

**Comment by PabloSB96** [comment]
A favor del cambio

**Comment by andresgomezvidal** [comment]
Creo que se puede cerrar

**Comment by PabloSB96** [comment]
Sí, considero que se puede cerrar también
