### ISSUE TITLE
Creación Planificación

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#20]
#### Descripción del cambio:
Planificación de todo el proyecto.

#### Objetivo del cambio:
Planificar adecuadamente los tiempos y responsabilidades del proyecto

#### Configuración afectada:
Proyecto_grupo_J/Proyecto/GrpJ_PLP_MemoriaProyecto.docx
Proyecto_grupo_J/Proyecto/GrpJ_ISI_Planificacion.pod

#### Comentario:
Debe durar como máximo 4 meses.
Debe detallar responsabilidades.

Las duraciones deben de ser como mínimo 1 día.
Debe haber mucho nivel de detalle, para que no se nos olvide nada esencial.
No debe haber colchones.

#### Gravedad (Seleccionar varias en caso de duda):
  - [x] Alta.
  - [] Media.
  - [] Baja.

**Comment by Lns-Prt** [comment]
Apruebo este cambio.

**Comment by andresgomezvidal** [comment]
Creo que por fin esto se puede cerrar

**Comment by PabloSB96** [comment]
Estoy de acuerdo. Se puede cerrar
