### ISSUE TITLE
Registrar el trabajo de la práctica

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#21]
#### Descripción del cambio:
Modificar los documentos para indicar el trabajo realizado en esta práctica

#### Objetivo del cambio:
En GrpJ_ISI_OrganizacionTrabajo.docx añadir información sobre:
-EDT y las descripciones de las hojas
-Planificación
-Personal y sueldos

En GrpJ_ISI_ReparticionTrabajo.pod añadir información sobre el trabajo realizado y el responsable.

#### Configuración afectada:
Proyecto_grupo_J/Practicas/GrpJ_ISI_OrganizacionTrabajo.docx
Proyecto_grupo_J/Practicas/GrpJ_ISI_ReparticionTrabajo.pod

#### Gravedad (Seleccionar varias en caso de duda):
  - [] Alta.
  - [] Media.
  - [x] Baja.

**Comment by Lns-Prt** [comment]
A favor de este cambio.

**Comment by Lns-Prt** [comment]
Terminado el cambio. ¿Dáis vuestra aprobación?

**Comment by PabloSB96** [comment]
Falta incluír imágen del cronograma en el documento

**Comment by andresgomezvidal** [comment]
Ok yo creo que esto ya está
