### ISSUE TITLE
Determinación de personal del proyecto

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#22]
#### Descripción del cambio:
Añadir un apartado nuevo a la memoria.

#### Objetivo del cambio:

Determinar el equipo de trabajo del proyecto y sus sueldos y horarios.

#### Configuración afectada:
Proyecto_grupo_J/Proyecto/GrpJ_PLP_MemoriaProyecto.docx

#### Comentario:
El realismo de los sueldos debe ser aproximado si es posible (margen de 1000€ entra bien), pero no hay que preocuparse mucho

#### Gravedad (Seleccionar varias en caso de duda):
  - [] Alta.
  - [x] Media.
  - [] Baja.

**Comment by andresgomezvidal** [comment]
http://www.calculatusueldo.com/calcula_tu_sueldo_bruto.htm
http://www.seg-social.es/Internet_1/Trabajadores/CotizacionRecaudaci10777/Basesytiposdecotiza36537/index.htm

**Comment by danielblanco96** [comment]
Acepto el cambio

**Comment by danielblanco96** [comment]
Añadidos los costes de los recursos. Propongo cerrar.

**Comment by andresgomezvidal** [comment]
Okay
