### ISSUE TITLE
Ajustar planificacion a los recursos

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#24]
#### Descripción del cambio:
Ajustar la planificación de la práctica anterior a los parámetros nuevos.

#### Objetivo del cambio:
Ajustarse a los requisitos sin reducir horas sin justificación.
Registrar las fechas de las entregas en la memoria (Restricciones del proyecto)

#### Configuración afectada:
Proyecto_grupo_J/Proyecto/GrpJ_ISI_Planificacion.pod
Proyecto_grupo_J/Proyecto/GrpJ_PLP_MemoriaProyecto.docx

#### Gravedad (Seleccionar varias en caso de duda):
  - [x] Alta.
  - [] Media.
  - [] Baja.

**Comment by andresgomezvidal** [comment]
Excelente, creo que se puede cerrar

**Comment by PabloSB96** [comment]
Estoy de acuerdo

**Comment by javisjavi** [comment]
Estoy de acuerdo con el cambio.
