### ISSUE TITLE
Plan de gestión RRHH

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#25]
#### Descripción del cambio:
Documentar toda la parte de RRHH

#### Configuración afectada:
Proyecto_grupo_J/Proyecto/GrpJ_PLP_MemoriaProyecto.docx

#### Gravedad (Seleccionar varias en caso de duda):
  - [x] Alta.
  - [] Media.
  - [] Baja.

**Comment by PabloSB96** [comment]
A favor del cambio

**Comment by PabloSB96** [comment]
Estoy de acuerdo

**Comment by javisjavi** [comment]
Estoy de acuerdo con el cambio.
