### ISSUE TITLE
Añadir el nuevo miembro al grupo

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#26]
#### Descripción del cambio:
Cambiar los documentos a partir de ahora para que mencionen también a Javier.

#### Objetivo del cambio:
Que se mencione a Javier a partir de ahora.

#### Configuración afectada:
Proyecto_grupo_J/Proyecto/GrpJ_PLP_MemoriaProyecto.docx
Proyecto_grupo_J/Practicas/GrpJ_ISI_OrganizacionTrabajo.docx
Proyecto_grupo_J/Practicas/GrpJ_ISI_ReparticionTrabajo.pod
Proyecto_grupo_J/Organizacion/GrpJ_PRO_PlanGC.docx
Posiblemente otros, por determinar

#### Comentario:
No es necesario hacerlo ahora (tiene que estar para la práctica final correctamente).
No es necesario hacer los commits solo para este issue, se pueden referenciar varios o hacerlo manualmente luego con un comentario.

#### Gravedad (Seleccionar varias en caso de duda):
  - [] Alta.
  - [x] Media.
  - [] Baja.

**Comment by PabloSB96** [comment]
A favor del cambio

**Comment by andresgomezvidal** [comment]
Excelente, creo que se puede cerrar

**Comment by javisjavi** [comment]
Estoy de acuerdo con el cambio.

**Comment by Lns-Prt** [comment]
Actualizados los documentos con el nuevo miembro. Solicito aprobación del cambio.

**Comment by andresgomezvidal** [comment]
Creo que se puede cerrar

**Comment by danielblanco96** [comment]
A favor del cierre
