### ISSUE TITLE
Registrar el trabajo de la práctica 4

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#27]
#### Descripción del cambio:
Modificar los documentos para indicar el trabajo realizado en esta práctica

### Objetivo del cambio:
Añadir información sobre:
#26 #25 #24 #28

### Configuración afectada:
Proyecto_grupo_J/Practicas/GrpJ_ISI_OrganizacionTrabajo.docx
Proyecto_grupo_J/Practicas/GrpJ_ISI_ReparticionTrabajo.pod

#### Gravedad (Seleccionar varias en caso de duda):
  - [] Alta.
  - [x] Media.
  - [] Baja.

**Comment by PabloSB96** [comment]
A favor del cambio

**Comment by andresgomezvidal** [comment]
Excelente, creo que se puede cerrar

**Comment by PabloSB96** [comment]
Estoy de acuerdo

**Comment by javisjavi** [comment]
De acuerdo con el cambio.
