### ISSUE TITLE
Cambios por la revisión

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#28]
#### Descripción del cambio:
Cambios en el trabajo hasta el momento por el feedback del profesor

#### Configuración afectada:
Proyecto_grupo_J/Proyecto/GrpJ_PLP_MemoriaProyecto.docx

#### Gravedad (Seleccionar varias en caso de duda):
  - [] Alta.
  - [x] Media.
  - [] Baja.

**Comment by PabloSB96** [comment]
A favor del cambio

**Comment by andresgomezvidal** [comment]
Excelente, creo que se puede cerrar

**Comment by PabloSB96** [comment]
Estoy de acuerdo

**Comment by javisjavi** [comment]
De acuerdo con el cambio.
