### ISSUE TITLE
Plan de Gestion de Riesgos

### ISSUE THREAD

**Issue by PabloSB96** [andresgomezvidal/gestion_de_proyectos#29]
#### Descripción del cambio:
Inclusión en la memoria del proyecto el plan de gestión de riesgos y  la hoja de cálculo de RiesgosIncidencias.

#### Objetivo del cambio:
Incluir en la memoria:
- Plan de gestión de riesgos
- Identificación de riesgos
- Análisis cualitativo
- Análisis cuantitativo
- Planificación, seguimiento y control

#### Configuración afectada:
- Proyecto/GrpJ_PLP_MemoriaProyecto.docx
- Proyecto/GrpJ_ISI_Planificacion.pod
- Proyecto/Grp_ISI_RiesgosIncidencias.ods

#### Gravedad (Seleccionar varias en caso de duda):
  - [x] Alta.
  - [ ] Media.
  - [ ] Baja.

**Comment by PabloSB96** [comment]
A favor del cambio

**Comment by andresgomezvidal** [comment]
Muy bien

**Comment by danielblanco96** [comment]
A favor del cambio

**Comment by PabloSB96** [comment]
Creo que se puede cerrar el issue

**Comment by andresgomezvidal** [comment]
Estoy de acuerdo

**Comment by javisjavi** [comment]
Estoy de acuerdo también
