### ISSUE TITLE
Documentos de estimaciones

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#3]
#### Descripción del cambio:
Documentación relativa a las diferentes estimaciones del proyecto

#### Objetivo del cambio:
Estimar apropiadamente los recursos y la duración de las actividades

#### Configuración afectada:
Proyecto_grupo_J/Proyecto/Estimación de Requisitos.ods
Proyecto_grupo_J/Proyecto/Estimación de Requisitos_subgrupo1.ods
Proyecto_grupo_J/Proyecto/Estimación de Requisitos_subgrupo2.ods

#### Comentario:
Necesario para la práctica 2.

El subgrupo 1 serán Pablo y Daniel
El subgrupo 2 serán Javi y Andrés

La puesta en común se hace por todo el equipo

#### Gravedad (Seleccionar varias en caso de duda):
  - [x] Alta.
  - [ ] Media.
  - [ ] Baja.

**Comment by Lns-Prt** [comment]
A favor del cambio.

**Comment by PabloSB96** [comment]
A favor del cambio.

**Comment by andresgomezvidal** [comment]
Creo que ya se puede por terminada esta rama temporal, integrandola en develop

**Comment by PabloSB96** [comment]
Ok, a favor de cerrar la rama
