### ISSUE TITLE
Registro del trabajo de la práctica 5

### ISSUE THREAD

**Issue by PabloSB96** [andresgomezvidal/gestion_de_proyectos#30]
#### Descripción del cambio:
Registrar el trabajo de la práctica 5

#### Objetivo del cambio:
Registrar el trabajo de la práctica 5

#### Configuración afectada:
Practicas/GrpJ_ISI_OrganizacionTrabajo.docx
Practicas/GrpJ_ISI_ReparticionTrabajo.pod

#### Gravedad (Seleccionar varias en caso de duda):
  - [ ] Alta.
  - [x] Media.
  - [ ] Baja.

**Comment by PabloSB96** [comment]
A favor del cambio

**Comment by andresgomezvidal** [comment]
Muy bien

**Comment by danielblanco96** [comment]
A favor del cambio

**Comment by andresgomezvidal** [comment]
Creo que se puede cerrar

**Comment by Lns-Prt** [comment]
Corregido el nombre del archivo del cronograma. Ahora sí que deberíamos cerrar.

**Comment by PabloSB96** [comment]
De acuerdo en cerrar
