### ISSUE TITLE
Modificar el RBS de la memoria

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#31]
#### Descripción del cambio:
El RBS de la sección "Estructura de Desglose de Recursos" de la memoria es incorrecto.

#### Objetivo del cambio:
Adaptarlo a las condiciones actuales del proyecto.

#### Configuración afectada:
Proyecto_grupo_J/Proyecto/GrpJ_PLP_MemoriaProyecto.docx 

#### Gravedad (Seleccionar varias en caso de duda):
  - [] Alta.
  - [] Media.
  - [x] Baja.

**Comment by PabloSB96** [comment]
A favor del cambio

**Comment by Lns-Prt** [comment]
Estoy a favor del cambio.

**Comment by andresgomezvidal** [comment]
Creo que se puede cerrar

**Comment by Lns-Prt** [comment]
Voto a favor del cierre.

**Comment by PabloSB96** [comment]
A favor del cierre.
