### ISSUE TITLE
Correcciones revisión práctica 6

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#32]
#### Descripción del cambio:
Modificar la documentación para adaptarse a las notas de interés de Efrén el viernes pasado.
Contrastar los objetivos con las notas tomadas para más información.
Se trabaja sobre el documento de drive de la práctica 7 (porque es el más actualizado).

#### Objetivo del cambio (incluyendo reparto de tareas):
**Todos:** al terminar revisar las exclusiones BASTANTE.

**Daniel Blanco:**
Mover los Objetivos del sistema, porque todavia no sabe cual es el alcance.
Diferenciar entre proyecto y producto:
	producto=producto software
	proyecto=algo más
Determinar si hemos detectado algun trabajo que necesite subcontratación o si podemos hacerlo todo con personal de nuestra empresa.
Planearse si poner algo más en el apartado de seguridad.
En la sección de Activos de los procesos:
Poner directorio plantillas.
Mover la informacion acerca de edificios etc a supuestos.
Quitar siglas ETT porque queda muy raro. Indicar de donde sale la fórmula.

**Pablo Sánchez:**
Ya que TODO LO QUE NO SE PONGA EN INCLUSIONES ESTÁ EXCLUIDO no se deben dejar cosas en el aire, como los idiomas.
Determinar claramente que Efrén y Taboada son supervisores y pertenecen a GEISOFT. Implica la modifiación de las tablas.

**Javier Porto:**
En la sección de Restricciones del proyecto:
Indicar de donde sale la monetaria.
Poner la de incrementos a X meses del proyecto
Añadir el nuevo RBS (commit 8e5ff7beedf3f8214d7227a5fa2c3b6fb6297bda) 
En supuestos poner algo como "queda excluida la compra de dispositivos moviles para ... porque los proporciona la USC".
Asegurarse de tener siempre roles en vez de nombres, porque no está determinado quien lleva cada tarea hasta que comienza el proyecto.

**Javier Martínez:**
En la sección Recursos para las actividades:
La estimacion que hacemos tiene que ver con tiempo y recursos humanos
La estimacion deberia estar en rrhh y la de tiempos en tiempos
Mover el EDT si hace falta.
Mover el calendario de rrhh a la sección de rrhh.
Corregir la matriz raci: A es Autoridad. Hay varias entradas incorrectas.

**Andrés Gómez** (esta parte la había hecho yo y es un poco desastre):
En la sección Factores ambientales:
Quitar referencias de la USC en nuestra empresa.
Nuevamente no mencionar nombres.
No soltar rollos, si no decir cosas generales como "no existe problema para hablar ingles".
Indicar los logísticos y supuestos claramente.
Quitar lo del jefe de proyecto a Málaga porque no sabemos quien va a ser.
Quitar la parte del 40% en la descripción del rol del jefe de proyecto.
Diferenciar correctamente entre Responsabilidades y Competencias.

#### Configuración afectada:
Proyecto_grupo_J/Proyecto/GrpJ_PLP_MemoriaProyecto.docx

#### Comentario:
Poner un comentario cada vez que se termina una parte o todo lo encargado, para poder controlar el progreso.

#### Gravedad (Seleccionar varias en caso de duda):
  - [] Alta.
  - [] Media.
  - [x] Baja.

**Comment by PabloSB96** [comment]
A favor del cambio.

**Comment by Lns-Prt** [comment]
Estoy a favor del cambio.

**Comment by danielblanco96** [comment]
Dejo en negrita los cambios que he completado. En cursiva las dudas que tengo

**Mover los Objetivos del sistema, porque todavía no sabe cual es el alcance.**

Diferenciar entre proyecto y producto: _No sé dónde hacerlo, ni tampoco fue muy claro el Efrén_
producto=producto software
proyecto=algo más

**Determinar si hemos detectado algún trabajo que necesite subcontratación o si podemos hacerlo todo con personal de nuestra empresa.** _En principio podemos hacerlo todo con personal de nuestra empresa, es lo que teníamos pensado. Como mucho personal de limpieza quizás?_

**Planearse si poner algo más en el apartado de seguridad.** _Añadí información que se me ocurrió, leedlo y se desea añadir más se añade_

En la sección de Activos de los procesos:
Poner directorio plantillas. _Ya está como anexo, no sé por qué hace falta_
**Mover la informacion acerca de edificios etc a supuestos.**. _Pasé a supuestos lo que me parecía, pero no estoy seguro al 100% de que sea todo_
**Quitar siglas ETT porque queda muy raro. Indicar de donde sale la fórmula.**

**Comment by PabloSB96** [comment]
Todos los cambios que tenía asignados, están hechos. Serían:
Ya que TODO LO QUE NO SE PONGA EN INCLUSIONES ESTÁ EXCLUIDO no se deben dejar cosas en el aire, como los idiomas.
Determinar claramente que Efrén y Taboada son supervisores y pertenecen a GEISOFT. Implica la modifiación de las tablas.

**Comment by andresgomezvidal** [comment]
He hecho mi parte y un trozo adicional (sin borrar nada solo cambiando colores) en relación al issue #39 de cambios en la planficación. No tengo claro si realmente he solucionado el problema de _"Diferenciar correctamente entre Responsabilidades y Competencias"_ porque creo que realmente era _Descripción_ en vez de _Responsabilidades_.

**Comment by Lns-Prt** [comment]
He realizado todos los cambios que se me asignaron. Bueno, en realidad algunos ya estaban hechos por otra persona. Se pueden ver en la memoria del proyecto en la carpeta Práctica8 de Drive.

**Comment by andresgomezvidal** [comment]
Creo que se puede cerrar

**Comment by javisjavi** [comment]
A favor de cerrarlo

**Comment by PabloSB96** [comment]
A favor del cierre.

**Comment by Lns-Prt** [comment]
A favor del cierre.
