### ISSUE TITLE
Modificación del Gantt

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#33]
#### Descripción del cambio:
Eliminar o modificar información del Gantt para adaptarse al nuevo estado del proyecto.

#### Objetivo del cambio:
En principio solo se me ocurre:
Quitar elementos de la sección de Gestión de Costes
  Poner la Gestión de la configuración en la Gestión de Proyectos

#### Configuración afectada:
Proyecto_grupo_J/Proyecto/GrpJ_ISI_Planificacion.pod

#### Gravedad (Seleccionar varias en caso de duda):
  - [] Alta.
  - [] Media.
  - [x] Baja.

**Comment by PabloSB96** [comment]
A favor del cambio

**Comment by danielblanco96** [comment]
A favor del cambio

**Comment by PabloSB96** [comment]
Creo que se puede cerrar el issue

**Comment by andresgomezvidal** [comment]
Creo que se puede cerrar el issue

**Comment by Lns-Prt** [comment]
Apruebo el cierre.
