### ISSUE TITLE
Plan de gestion de costes

### ISSUE THREAD

**Issue by PabloSB96** [andresgomezvidal/gestion_de_proyectos#34]
#### Descripción del cambio:
Introducir en la memoria lo referente a la gestión de costes

#### Objetivo del cambio:
Realizar la planificación de costes, estimacion de costes, determinación del presupuesto y control de costes.

#### Configuración afectada:
/Proyecto/GrpJ_PLP_MemoriaProyecto.docx
/Proyecto/GrpJ_PLP_AnalisisEconomico.ods
/Proyecto/GrpJ_ISI_LineaBaseCostosRecursos.ods

#### Gravedad (Seleccionar varias en caso de duda):
  - [ ] Alta.
  - [x] Media.
  - [ ] Baja.

**Comment by danielblanco96** [comment]
A favor del cambio

**Comment by Lns-Prt** [comment]
Estoy a favor del cambio.

**Comment by PabloSB96** [comment]
Creo que se puede cerrar el issue.

**Comment by andresgomezvidal** [comment]
Creo que se puede cerrar el issue

**Comment by Lns-Prt** [comment]
Apruebo el cierre.
