### ISSUE TITLE
Registro del trabajo de la práctica 6

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#35]
#### Objetivo del cambio:
Registrar el trabajo de la práctica 6

#### Configuración afectada:
Practicas/GrpJ_ISI_OrganizacionTrabajo.docx
Practicas/GrpJ_ISI_ReparticionTrabajo.pod

#### Gravedad (Seleccionar varias en caso de duda):
  - [] Alta.
  - [x] Media.
  - [] Baja.

**Comment by PabloSB96** [comment]
A favor del cambio

**Comment by Lns-Prt** [comment]
Estoy a favor del cambio.

**Comment by andresgomezvidal** [comment]
Referencia a los cambios en el commit de082d1f9d6efeef33de2ad107ab8318f9bec863

**Comment by andresgomezvidal** [comment]
Creo que se puede cerrar el issue

**Comment by Lns-Prt** [comment]
Apruebo el cierre del issue.

**Comment by PabloSB96** [comment]
A favor del cierre
