### ISSUE TITLE
Actualizar documento de Análisis económico

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#36]
#### Objetivo del cambio:
Arreglo de errores y reducción del presupuesto.

#### Configuración afectada:
Proyecto/GrpJ_PLP_AnalisisEconomico.ods

#### Gravedad (Seleccionar varias en caso de duda):
  - [] Alta.
  - [x] Media.
  - [] Baja.

**Comment by PabloSB96** [comment]
A favor del cambio

**Comment by danielblanco96** [comment]
A favor del cambio

**Comment by andresgomezvidal** [comment]
Creo que ya se puede cerrar

**Comment by PabloSB96** [comment]
A favor del cierre.

**Comment by danielblanco96** [comment]
A favor del cierre
