### ISSUE TITLE
Gestión de las Comunicaciones

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#37]
#### Descripción del cambio:
Mirar la traspa 11 (y posteriores) para ver lo que quiere de cada uno de los 3 puntos principales.

plan de gestion de las comunicaciones
	lo hizo Pablo en otra práctica
		mejorarlo
comunicaciones del proyecto

Estaría bien poner la fórmula n(n-1)/2 (del número de canales de comunicación).

mirar si poner alguna plantilla
lecciones aprendidas
buenas practicas

Se recomienda mucho mirar las notas tomadas en clase.

#### Objetivo del cambio:
Efectuar los cambios necesarios para la práctica 7

#### Configuración afectada:
Proyecto/GrpJ_PLP_MemoriaProyecto.docx

#### Gravedad (Seleccionar varias en caso de duda):
  - [] Alta.
  - [x] Media.
  - [] Baja.

**Comment by PabloSB96** [comment]
A favor del cambio

**Comment by Lns-Prt** [comment]
Estoy a favor del cambio.

**Comment by PabloSB96** [comment]
Creo que se puede cerrar el issue

**Comment by andresgomezvidal** [comment]
Creo que se puede cerrar

**Comment by Lns-Prt** [comment]
Voto el cierre.
