### ISSUE TITLE
Registro del trabajo de la práctica 7

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#38]
#### Descripción del cambio:
Registrar el trabajo de la práctica 7

#### Objetivo del cambio:
Practicas/GrpJ_ISI_OrganizacionTrabajo.docx
Practicas/GrpJ_ISI_ReparticionTrabajo.pod

#### Gravedad (Seleccionar varias en caso de duda):
  - [] Alta.
  - [] Media.
  - [x] Baja.

**Comment by PabloSB96** [comment]
A favor del cambio

**Comment by Lns-Prt** [comment]
Estoy a favor del cambio.

**Comment by Lns-Prt** [comment]
Todos los cambios fueron aplicados.

**Comment by andresgomezvidal** [comment]
Creo que se puede dar por cerrado

**Comment by Lns-Prt** [comment]
Voto el cierre.

**Comment by PabloSB96** [comment]
A favor del cierre
