### ISSUE TITLE
Cambios en la memoria para la práctica final

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#39]
#### Descripción del cambio:
  - [x] Creo que hay un problema de enfoque de la memoria, ahora mismo está escrita a modo de relato de progreso de las prácticas en vez de enfoque de memoria de un solo trabajo (por ejemplo el apartado de cambios en la planificación). En el caso concreto de _cambios en la planificación_ se puede dejar esa información (porque demuestra que trabajamos y explica cómo) pero poniéndolo más profesional, como si fuese un proyecto real, por ejemplo indicando que se hizo una planificación inicial que luego un supervisor dio por mala e hizo falta volver a hacerla.
  - [x] Hace falta añadir la información relativa a la última práctica.
  - [x] Hay que hacer todavía cambios de correcciones de feedback.
  - [x] Hay que unificar el formato (por ejemplo índice con o sin todo mayúsculas).
  - [x] Hay que determinar claramente las horas anuales que podría como mucho dedicar cada rol al proyecto, es decir, hacer el cálculo con respecto a nuestra duración de proyecto y multiplicarlo por el porcentaje de tiempo que pueden emplear (40, 60 o 100%).
  - [x] Hay que añadir más términos al glosario y ponerlo por orden alfabético.
  - [x] Hay que actualizar el presupuesto en todos los puntos de la memoria, como en "Restricciones del proyecto" y la traspa 160.
  - [x] Hay figuras que no tienen indicación de que lo son con su descripción y otras sí. Por ejemplo en "Casos de uso del sistema". **Lo estaba haciendo Javier Martínez**.
  - [x] Sigue habiendo menciones específicas a nombres en vez de roles, como en "Registro de interesados" y en la página 83, donde aparece el correo de un empleado particular como jefe de proyecto. Similarmente en la traspa 85.
  - [x] En la traspa 95 aparece una fórmula que creo recordar no le gustaba.
  - [x] Hay que cambiar el organigrama (tiene nombres en vez de roles) y el RBS. **Lo estaba haciendo Dani.**
  - [x] En el calendario indicar más claramente el mes del que se trata.
  - [x] Usar un formato unificado a lo largo del documento para referirse a los roles, por ejemplo aparecen Analista/Diseñador y Analista Diseñador.
  - [x] En la página 118 hay un paréntesis muy raro cerca de "nube".
  - [x] En la tabla de "Estimacón de los costos" poner "Rol" en vez de "Nombre".
  - [x] Poner en el documento de prácticas que no se cambia el acta porque dijo Taboada que no se cambiaba aunque tenemos un miembro nuevo. También explicar que se creó previamente, porque seguimos un proceso de práctica para aprender por tanto hay que partir de cierto material.
  - [x] Añadir documento de planificación de la práctica anterior a su cambio, llamarle de forma diferenciada y solo tenerlo en la carpeta de la empresa (no el cliente). Referenciar el documento en el apartado de "Cambios en la planificación".
  - [x] Añadir las plantillas de la práctica anterior que nos interesen y referenciarlas. Crear la plantilla de acta.

#### Configuración afectada:
Proyecto/GrpJ_PLP_MemoriaProyecto.docx 

#### Gravedad (Seleccionar varias en caso de duda):
  - [x] Alta.
  - [] Media.
  - [] Baja.

**Comment by Lns-Prt** [comment]
Estoy a favor del cambio.

**Comment by javisjavi** [comment]
A favor del cambio

**Comment by andresgomezvidal** [comment]
Problema actual: el organigrama y el RBS son lo mismo

**Comment by andresgomezvidal** [comment]
Pablo
  - [ ] Modificar el documento de línea base de costos para adaptarse al nuevo presupuesto.
  - [ ] Actualizar la documentación relativa a la línea base de costos en la memoria, como la gráfica.

Dani
  - [ ] Informe de desempeño: Plantilla, explicación breve y ubicarlo en el documento
  - [ ] Poner de forma más integrada las buenas prácticas de "Plan de gestión de costes"
  - [ ] En "Plan de gestión de costes" poner trozos del excel, bolsa de desplazamiento, y otra de riesgos, poner precios

Andres
  - [ ] Teoría a cosas útiles del proyecto en la parte de Plan de costes
  - [ ] Poner de forma más integrada las lecciones aprendidas de "Plan de gestión de costes"
  - [ ] Unidades de medida euro , nivel de exactitud +-10% , umbral de control 10% de desvio

Javier Porto
  - [ ] Teoría a cosas útiles del proyecto en la parte de Comunicaciones
		quiere saber quien recibe cada informacion
		quiere saber quien es el responsable de cada comunicacion
		interesados y comunicaciones tiene que estar casi fusionado
  - [ ] Poner de forma más integrada las buenas prácticas de "Activos de los procesos de la Organización"
  - [ ] En la parte de Comunicaciones arreglar la tabla de euros de sueldo, para €/hora y mirar lo de los valores corectos (aparentemente están anuales)

Javier Martinez
  - [ ] Teoría a cosas útiles del proyecto en la parte de Herramientas y técnicas
  - [ ] Poner de forma más integrada las lecciones aprendidas de "Activos de los procesos de la Organización"
  - [ ] Corregir "por ultimo se econtraria la computacion de los costes indirectos": se imputan, no se computan
  - [ ] Aclarar, porque Efrén no sabe si hablamos de las tensiones de tesoreria en el Plan de gestión de costos

**Comment by PabloSB96** [comment]
Creo que sería conveniente mover el apartado de **Planificación** entero al documento de Practicas/RepartoTrabajo, siguiendo lo que nos dijo Efrén en clase.

**Comment by andresgomezvidal** [comment]
Creo que se puede cerrar

**Comment by Lns-Prt** [comment]
Voto por cerrar.

**Comment by javisjavi** [comment]
A favor del cierre.
