### ISSUE TITLE
Ampliación de los requisitos

### ISSUE THREAD

**Issue by Lns-Prt** [andresgomezvidal/gestion_de_proyectos#4]
#### Descripción del cambio:
Añadir un nuevo Requisito de Información: Informe.
Añadir dos Requisitos Funcionales: Mostrar informes y Eliminar un informe.

#### Objetivo del cambio:
Actualizar el catálogo de requisitos con los nuevos requisitos.
Actualizar el diagrama de casos de uso del subsistema de Generación de informes.
Actualizar la memoria del proyecto con los nuevos requisitos, casos de uso y diagrama de casos de uso, y matrices de trazabilidad. 

#### Configuración afectada:
Proyecto_grupo_J/Proyecto/Catalogo de Requisitos.xlsx
Proyecto_grupo_J/Proyecto/Memoria_Proyecto.docx
Proyecto_grupo_J/Proyecto/Diagramas/requisitos_funcionales.mdj
Proyecto_grupo_J/Proyecto/Diagramas/jpg/Model__Generacion de informes_4.jpg

#### Comentario:
Necesario para la práctica 2

#### Gravedad (Seleccionar varias en caso de duda):
  - [x] Alta.
  - [ ] Media.
  - [ ] Baja.

**Comment by danielblanco96** [comment]
Acepto el cambio

**Comment by andresgomezvidal** [comment]
Estoy de acuerdo

**Comment by PabloSB96** [comment]
Estoy de acuerdo

**Comment by Lns-Prt** [comment]
Ya he aplicado todos los cambios sobre los documentos del proyecto. ¿Aprobáis los cambios?

**Comment by andresgomezvidal** [comment]
Como jefe de proyecto doy fe de que está bien y voy a añadirlo a develop
