### ISSUE TITLE
Separación del documento del cliente y reorganización de carpetas

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#40]
#### Objetivo del cambio:

Crear un nuevo documento de memoria para el cliente, con la información necesaria solamente.

Modificar las carpetas a la siguiente estructura:

Proyecto
-     Equipo: archivos esenciales del entorno de trabajo del proyecto. Incluyen el trabajo presentado al cliente, pero completo.
-     Cliente: Productos que se entregan al cliente. Como memoria y planning solo con información de interés para el cliente.
Organización

-     Activos Organización: Plantillas de la organización para elaborar documentos necesarios en la ejecución de los procesos.
-     Procesos de la Organización: Solo contiene este archivo (GrpJ_PRO_PlanGC.docx), es decir la Gestión de la Configuración.

Prácticas

#### Configuración afectada:

Proyecto/
Proyecto/Cliente/GrpJ_PLP_MemoriaProyecto.docx
Organización/

#### Comentario:

Creo que lo mejor es terminar la otra memoria primero y luego quitarle cosas, pero creo que también se puede hacer bien de forma paralela porque lo que hagamos en la otra en muchos casos al cliente le da igual.

#### Gravedad (Seleccionar varias en caso de duda):
  - [x] Alta.
  - [] Media.
  - [] Baja.

**Comment by javisjavi** [comment]
A favor del cambio

**Comment by PabloSB96** [comment]
A favor del cambio

**Comment by andresgomezvidal** [comment]
He actualizado la GC en su nueva carpeta de esta rama para que no haya conflicto luego al hacer el merge

**Comment by andresgomezvidal** [comment]
Poner las lecciones aprendidas y buenas prácticas en la carpeta de activos de la organización, en un documento nuevo

**Comment by andresgomezvidal** [comment]
Creo que se puede cerrar

**Comment by PabloSB96** [comment]
A favor del cierre

**Comment by javisjavi** [comment]
A favor del cierre.
