### ISSUE TITLE
Registro del trabajo de la practica final

### ISSUE THREAD

**Issue by PabloSB96** [andresgomezvidal/gestion_de_proyectos#41]
#### Descripción del cambio:
Registrar el trabajo de la practica 8, la final, e incluir una explicación en el documento sobre porque el nuevo miembro no aparece en el acta de constitución.

#### Objetivo del cambio:
-Registrar trabajo práctica final
-Explicación falta miembro en el acta de constitución

#### Configuración afectada:
Practicas/GrpJ_ISI_OrganizacionTrabajo.docx
Practicas/GrpJ_ISI_ReparticionTrabajo.pod

#### Gravedad (Seleccionar varias en caso de duda):
  - [] Alta.
  - [x] Media.
  - [] Baja.

**Comment by PabloSB96** [comment]
A favor del cambio.

**Comment by andresgomezvidal** [comment]
Me parece bien

**Comment by danielblanco96** [comment]
A favor del cambio

**Comment by PabloSB96** [comment]
Creo que se puede cerrar

**Comment by andresgomezvidal** [comment]
Creo que lo podemos cerrar ya

**Comment by danielblanco96** [comment]
A favor del cierre
