### ISSUE TITLE
Modificación de los casos de uso de informes

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#5]
#### Descripción del cambio:
Se detectó una discrepancia en la funcionalidad de los informes y es necesario solucionarlo en la documentación.

#### Objetivo del cambio:
Corregir los casos de uso de los informes.

#### Configuración afectada:
Proyecto_grupo_J/Proyecto/Memoria_Proyecto.doc

#### Comentario:
Como se acordó oralmente el informe debe ser lo más automatizado posible

#### Gravedad (Seleccionar varias en caso de duda):
  - [ ] Alta.
  - [ ] Media.
  - [x] Baja.

**Comment by PabloSB96** [comment]
Estoy de acuerdo

**Comment by PabloSB96** [comment]
Cambio finalizado. Se aprueba?

**Comment by andresgomezvidal** [comment]
Considero que https://github.com/andresgomezvidal/gestion_de_proyectos/commit/d91f89d7e24fd7522e4c1b740306a193d925e4ba se puede integrar en develop
