### ISSUE TITLE
Añadir requisitos asociados

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#6]
#### Descripción del cambio:
Rellenar el campo **Requisitos Asociados** en las tablas de requisitos de información y ampliar el campo homónimo en las tablas de los casos de uso.

#### Objetivo del cambio:
Se añaden las relaciones necesarias

#### Configuración afectada:
Proyecto_grupo_J/Proyecto/Memoria_Proyecto.doc

#### Gravedad (Seleccionar varias en caso de duda):
  - [ ] Alta.
  - [x] Media.
  - [ ] Baja.

**Comment by PabloSB96** [comment]
Estoy de acuerdo

**Comment by Lns-Prt** [comment]
La memoria del proyecto está actualizada. ¿Aprobáis el cambio?

**Comment by andresgomezvidal** [comment]
ok

**Comment by PabloSB96** [comment]
ok
