### ISSUE TITLE
Estructura de desglose de Recursos

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#7]
#### Descripción del cambio:
Este documento permite la representación jerárquica de los recursos por categoría y tipo

#### Objetivo del cambio:
Documentación del desglose de los recursos

#### Configuración afectada:
Proyecto_grupo_J/Proyecto/Desglose de Recursos.docx

#### Comentario:
Debe entregarse para la práctica 2

#### Gravedad (Seleccionar varias en caso de duda):
  - [ ] Alta.
  - [x] Media.
  - [ ] Baja.

**Comment by PabloSB96** [comment]
Estoy a favor de introducir el cambio

**Comment by andresgomezvidal** [comment]
Creo que se puede cerrar la rama

**Comment by andresgomezvidal** [comment]
Creo que se puede cerrar

**Comment by danielblanco96** [comment]
Ok
