### ISSUE TITLE
Registro de Incidentes

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#8]
#### Descripción del cambio:
Creación de los documentos necesarios

#### Objetivo del cambio:
Documentar el proceso de Registro de Incidentes

#### Configuración afectada:
Proyecto_grupo_J/Proyecto/Registro de Incidentes.docx
Proyecto_grupo_J/Proyecto/Memoria_Proyecto.doc

#### Comentario:
Necesario para la práctica 2

#### Gravedad (Seleccionar varias en caso de duda):
  - [ ] Alta.
  - [x] Media.
  - [ ] Baja.

**Comment by danielblanco96** [comment]
Acepto el cambio

**Comment by danielblanco96** [comment]
Finalizado.

**Comment by andresgomezvidal** [comment]
En la memoria del proyecto falta actualizar la versión de la cabecera y comentar el cambio realizado en esta versión al principio de la memoria.

**Comment by danielblanco96** [comment]
Cambios realizados.

**Comment by andresgomezvidal** [comment]
Voy a volver a ser pesado, pero debería ser la versión 1.3, que no es solo culpa tuya porque viene de antes

**Comment by andresgomezvidal** [comment]
Me acabo de dar cuenta de que falta la tabla que importaba de verdad
