### ISSUE TITLE
Actualizar Organización del trabajo de la practica

### ISSUE THREAD

**Issue by andresgomezvidal** [andresgomezvidal/gestion_de_proyectos#9]
#### Descripción del cambio:
Además de lo obvio (resumir el trabajo realizado en la práctica) hay que:
Relacionar/justificar los factores de corrección de la Estimación de Requisitos brevemente.
Explicar que las Solicitudes de Cambio no son necesarias porque se emplean issues para esta labor.
Explicar que actualizaciones explicitadas en los mismos Documentos del Proyecto no son necesarias porque quedan registrados en Git automáticamente, pero como excepción se hace en casos importantes como la GC.

#### Objetivo del cambio:
Documentar y explicar los cambios realizados en esta práctica 2

#### Configuración afectada:
Proyecto_grupo_J/Practicas/Organización del trabajo de la practica.docx

#### Comentario:
Necesario para la práctica 2.
Se recomienda hacerlo al final, para no sobreescribirse más tarde.

#### Gravedad (Seleccionar varias en caso de duda):
  - [x] Alta.
  - [ ] Media.
  - [ ] Baja.

**Comment by PabloSB96** [comment]
A favor del cambio

**Comment by andresgomezvidal** [comment]
Espléndido!
Cerremos esto!

**Comment by PabloSB96** [comment]
Perfecto
